version: '3.8'
services:

  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    networks:
      - ontograph-test
    ports:
      - 5060:8080
    volumes:
      - blazegraph-data:/data

volumes:
  blazegraph-data:

networks:
  ontograph-test:
    name: ontograph-test